# Generated by Django 5.2.15 on 2026-07-27 07:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Session key')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('converted', 'Оформлений'), ('abandoned', 'Покинутий')], default='active', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Кошик',
                'verbose_name_plural': 'Кошики',
                'db_table': 'commerce_cart',
                'indexes': [models.Index(condition=models.Q(('status', 'active')), fields=['session_key'], name='commerce_cart_active_sess')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('payment_status', models.CharField(choices=[('awaiting', 'Очікує оплати'), ('paid', 'Оплачено'), ('failed', 'Помилка оплати')], db_index=True, default='awaiting', max_length=20, verbose_name='Статус оплати')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Імʼя')),
                ('customer_email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('customer_phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('customer_comment', models.TextField(blank=True, default='', verbose_name='Коментар')),
                ('shipping_method', models.CharField(choices=[('np_warehouse', 'Нова Пошта — відділення'), ('np_poshtomat', 'Нова Пошта — поштомат'), ('pickup', 'Самовивіз')], max_length=20, verbose_name='Доставка')),
                ('np_city_ref', models.CharField(blank=True, default='', max_length=64, verbose_name='НП city ref')),
                ('np_city_name', models.CharField(blank=True, default='', max_length=255, verbose_name='НП місто')),
                ('np_warehouse_ref', models.CharField(blank=True, default='', max_length=64, verbose_name='НП warehouse ref')),
                ('np_warehouse_name', models.CharField(blank=True, default='', max_length=255, verbose_name='НП відділення')),
                ('np_area_ref', models.CharField(blank=True, default='', max_length=64, verbose_name='НП area ref')),
                ('subtotal_uah', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Підсумок')),
                ('shipping_uah', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Доставка (UAH)')),
                ('total_uah', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Разом')),
                ('payment_provider', models.CharField(choices=[('liqpay', 'LiqPay')], default='liqpay', max_length=20, verbose_name='Провайдер')),
                ('payment_external_id', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='External payment id')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачено о')),
                ('locale', models.CharField(default='uk', max_length=5, verbose_name='Мова')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='commerce.cart', verbose_name='Кошик')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'db_table': 'commerce_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=64, verbose_name='Артикул (snapshot)')),
                ('product_name', models.CharField(max_length=255, verbose_name='Назва (snapshot)')),
                ('qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість')),
                ('unit_price_uah', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна за од.')),
                ('line_total_uah', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума рядка')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='Нота')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
                'db_table': 'commerce_order_item',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('from_status', models.CharField(blank=True, default='', max_length=20, verbose_name='Зі статусу')),
                ('to_status', models.CharField(max_length=20, verbose_name='У статус')),
                ('note', models.TextField(blank=True, default='', verbose_name='Примітка')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_logs', to=settings.AUTH_USER_MODEL, verbose_name='Хто змінив')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='commerce.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Лог статусу замовлення',
                'verbose_name_plural': 'Логи статусів замовлень',
                'db_table': 'commerce_order_status_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість')),
                ('unit_price_uah', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ціна за од.')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.cart', verbose_name='Кошик')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cart_items', to='catalog.product', verbose_name='Нота')),
            ],
            options={
                'verbose_name': 'Позиція кошика',
                'verbose_name_plural': 'Позиції кошика',
                'db_table': 'commerce_cart_item',
                'constraints': [models.UniqueConstraint(fields=('cart', 'product'), name='commerce_cart_item_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='commerce_or_status_50df41_idx'),
        ),
    ]
