# Generated by Django 5.2.15 on 2026-07-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('to_email', models.EmailField(max_length=254, verbose_name='Кому')),
                ('template_key', models.CharField(choices=[('order_created_admin', 'Нове замовлення (адмін)'), ('lead_created_admin', 'Звернення (адмін)'), ('order_status_customer', 'Статус замовлення (клієнт)')], max_length=64, verbose_name='Шаблон')),
                ('related_object_type', models.CharField(blank=True, default='', max_length=40, verbose_name='Тип обʼєкта')),
                ('related_object_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID обʼєкта')),
                ('resend_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Resend id')),
                ('status', models.CharField(choices=[('queued', 'В черзі'), ('sent', 'Надіслано'), ('failed', 'Помилка')], default='queued', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Помилка')),
            ],
            options={
                'verbose_name': 'Лог email',
                'verbose_name_plural': 'Логи email',
                'db_table': 'notifications_email_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
