# Generated by Django 5.2.15 on 2026-07-27 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('provider', models.CharField(choices=[('liqpay', 'LiqPay')], default='liqpay', max_length=20, verbose_name='Провайдер')),
                ('event_type', models.CharField(choices=[('callback', 'Callback'), ('redirect_return', 'Redirect return')], max_length=40, verbose_name='Тип події')),
                ('external_id', models.CharField(blank=True, default='', max_length=128, verbose_name='External id')),
                ('idempotency_key', models.CharField(max_length=128, unique=True, verbose_name='Idempotency key')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('processed_ok', models.BooleanField(default=False, verbose_name='Оброблено успішно')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='commerce.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Подія оплати',
                'verbose_name_plural': 'Події оплати',
                'db_table': 'payments_event',
                'ordering': ['-created_at'],
            },
        ),
    ]
