# Generated by Django 5.2.15 on 2026-07-27 07:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('name_uk', models.CharField(max_length=255, verbose_name='Назва (UK)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Назва (EN)')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Композитор',
                'verbose_name_plural': 'Композитори',
                'db_table': 'catalog_composer',
                'ordering': ['sort_order', 'name_uk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('name_uk', models.CharField(max_length=255, verbose_name='Назва (UK)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Назва (EN)')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Формат',
                'verbose_name_plural': 'Формати',
                'db_table': 'catalog_format',
                'ordering': ['sort_order', 'name_uk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title', models.CharField(blank=True, default='', max_length=512, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, default='', verbose_name='SEO description')),
                ('name_uk', models.CharField(max_length=255, verbose_name='Назва (UK)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Назва (EN)')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанри',
                'db_table': 'catalog_genre',
                'ordering': ['sort_order', 'name_uk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title', models.CharField(blank=True, default='', max_length=512, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, default='', verbose_name='SEO description')),
                ('name_uk', models.CharField(max_length=255, verbose_name='Назва (UK)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Назва (EN)')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Інструмент',
                'verbose_name_plural': 'Інструменти',
                'db_table': 'catalog_instrument',
                'ordering': ['sort_order', 'name_uk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('name_uk', models.CharField(max_length=255, verbose_name='Назва (UK)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Назва (EN)')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Рівень складності',
                'verbose_name_plural': 'Рівні складності',
                'db_table': 'catalog_level',
                'ordering': ['sort_order', 'name_uk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title', models.CharField(blank=True, default='', max_length=512, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, default='', verbose_name='SEO description')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='Артикул')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('name_uk', models.CharField(max_length=255, verbose_name='Назва (UK)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Назва (EN)')),
                ('description_uk', models.TextField(blank=True, default='', verbose_name='Опис (UK)')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='Опис (EN)')),
                ('price_uah', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ціна (UAH)')),
                ('stock_qty', models.PositiveIntegerField(default=0, verbose_name='Залишок')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярне')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публікації')),
                ('composer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.composer', verbose_name='Композитор')),
                ('format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.format', verbose_name='Формат')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.level', verbose_name='Рівень')),
            ],
            options={
                'verbose_name': 'Нота',
                'verbose_name_plural': 'Ноти',
                'db_table': 'catalog_product',
                'ordering': ['-published_at', 'name_uk'],
            },
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('kind', models.CharField(choices=[('preview', 'Превʼю фрагмента')], default='preview', max_length=20, verbose_name='Тип')),
                ('file', models.FileField(max_length=512, upload_to='catalog/previews/', verbose_name='Файл')),
                ('title_uk', models.CharField(blank=True, default='', max_length=255, verbose_name='Назва (UK)')),
                ('title_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Назва (EN)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='catalog.product', verbose_name='Нота')),
            ],
            options={
                'verbose_name': 'Файл ноти',
                'verbose_name_plural': 'Файли нот',
                'db_table': 'catalog_product_file',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.genre')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Нота ↔ жанр',
                'verbose_name_plural': 'Ноти ↔ жанри',
                'db_table': 'catalog_product_genre',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='products', through='catalog.ProductGenre', to='catalog.genre', verbose_name='Жанри'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('image', models.ImageField(max_length=512, upload_to='catalog/products/', verbose_name='Зображення')),
                ('alt_uk', models.CharField(blank=True, default='', max_length=255, verbose_name='Alt (UK)')),
                ('alt_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Alt (EN)')),
                ('is_main', models.BooleanField(default=False, verbose_name='Обкладинка')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Нота')),
            ],
            options={
                'verbose_name': 'Зображення ноти',
                'verbose_name_plural': 'Зображення нот',
                'db_table': 'catalog_product_image',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.instrument')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Нота ↔ інструмент',
                'verbose_name_plural': 'Ноти ↔ інструменти',
                'db_table': 'catalog_product_instrument',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='instruments',
            field=models.ManyToManyField(blank=True, related_name='products', through='catalog.ProductInstrument', to='catalog.instrument', verbose_name='Інструменти'),
        ),
        migrations.AddConstraint(
            model_name='productgenre',
            constraint=models.UniqueConstraint(fields=('product', 'genre'), name='catalog_product_genre_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('product',), name='catalog_product_image_one_main'),
        ),
        migrations.AddConstraint(
            model_name='productinstrument',
            constraint=models.UniqueConstraint(fields=('product', 'instrument'), name='catalog_product_instrument_uniq'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_published', '-published_at'], name='catalog_pro_is_publ_267ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_popular'], name='catalog_pro_is_popu_31143a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_new'], name='catalog_pro_is_new_087fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['composer'], name='catalog_pro_compose_e121f5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['level'], name='catalog_pro_level_i_b3c507_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['format'], name='catalog_pro_format__2ca187_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price_uah__gte', 0)), name='catalog_product_price_uah_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock_qty__gte', 0)), name='catalog_product_stock_qty_gte_0'),
        ),
    ]
