# Generated by Django 5.2.15 on 2026-07-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge_text',
            field=models.CharField(blank=True, default='', help_text='Напр. NEW, BESTSELLER, 25% OFF. Порожньо — без бейджа.', max_length=32, verbose_name='Бейдж на обкладинці'),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_tone',
            field=models.CharField(blank=True, choices=[('yellow', 'Жовтий'), ('maroon', 'Бордовий'), ('blue', 'Синій'), ('gold', 'Золотий')], default='yellow', max_length=16, verbose_name='Колір бейджа'),
        ),
    ]
