# Generated by Django 5.2.15 on 2026-07-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_card_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='badge_text',
            field=models.CharField(blank=True, default='', help_text='Оберіть NEW, BESTSELLER, 25% OFF або введіть свій текст. Порожньо — без бейджа.', max_length=32, verbose_name='Бейдж на обкладинці'),
        ),
        migrations.AlterField(
            model_name='product',
            name='badge_tone',
            field=models.CharField(blank=True, choices=[('', '— без кольору —'), ('yellow', 'Жовтий'), ('maroon', 'Бордовий'), ('blue', 'Синій'), ('gold', 'Золотий')], default='yellow', help_text='Колір стрічки на обкладинці картки товару.', max_length=16, verbose_name='Колір бейджа'),
        ),
    ]
