# Generated by Django 5.2.15 on 2026-07-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_badge_presets_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('file', models.FileField(max_length=512, upload_to='catalog/imports/', verbose_name='Файл')),
                ('format', models.CharField(blank=True, choices=[('csv', 'CSV'), ('yml', 'YML/XML')], default='', help_text='Порожньо — визначити за розширенням файлу.', max_length=8, verbose_name='Формат')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('running', 'Виконується'), ('done', 'Завершено'), ('failed', 'Помилка')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='Створено')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='Оновлено')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Пропущено')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Помилок')),
                ('report_json', models.JSONField(blank=True, default=dict, verbose_name='Звіт')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Повідомлення помилки')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Старт')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершення')),
            ],
            options={
                'verbose_name': 'Імпорт товарів',
                'verbose_name_plural': 'Імпорт товарів',
                'db_table': 'catalog_product_import_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, default='', help_text='EAN/ISBN тощо. Порожньо дозволено; непорожні значення мають бути унікальними.', max_length=64, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='product',
            name='badge_text',
            field=models.CharField(blank=True, default='', help_text='NEW, BESTSELLER, 25% OFF або свій текст. Порожньо — без бейджа.', max_length=32, verbose_name='Бейдж на обкладинці'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name_uk', 'composer'], name='catalog_pro_name_uk_846ff2_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('barcode',), name='catalog_product_barcode_uniq_nonzero'),
        ),
    ]
