# Generated by Django 5.2.15 on 2026-07-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_barcode_and_import_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Рекомендований розмір: 800×1200 px. Значно більші фото автоматично обрізаються та стискаються. JPG/PNG → WebP.', max_length=512, upload_to='catalog/products/', verbose_name='Зображення'),
        ),
    ]
