# Generated by Django 5.2.15 on 2026-07-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Імʼя')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, default='', verbose_name='Повідомлення')),
                ('page_url', models.CharField(blank=True, default='', max_length=512, verbose_name='URL сторінки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Опрацьовано')),
            ],
            options={
                'verbose_name': 'Звернення',
                'verbose_name_plural': 'Звернення',
                'db_table': 'content_contact_lead',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title', models.CharField(blank=True, default='', max_length=512, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, default='', verbose_name='SEO description')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('title_uk', models.CharField(max_length=255, verbose_name='Заголовок (UK)')),
                ('title_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок (EN)')),
                ('body_uk', models.TextField(verbose_name='Текст (UK)')),
                ('body_en', models.TextField(blank=True, default='', verbose_name='Текст (EN)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Сторінка',
                'verbose_name_plural': 'Сторінки',
                'db_table': 'content_page',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('site_name', models.CharField(default='NotenHaus', max_length=255, verbose_name='Назва сайту')),
                ('logo', models.ImageField(blank=True, max_length=512, null=True, upload_to='content/logo/', verbose_name='Логотип')),
                ('contacts_json', models.JSONField(default=dict, verbose_name='Контакти')),
                ('admin_notify_email', models.EmailField(max_length=254, verbose_name='Email адміна для сповіщень')),
                ('notify_customer_on_status', models.BooleanField(default=True, verbose_name='Листи клієнту при зміні статусу')),
                ('default_locale', models.CharField(default='uk', max_length=5, verbose_name='Мова за замовчуванням')),
                ('robots_txt', models.TextField(blank=True, default='', verbose_name='robots.txt')),
                ('extra_json', models.JSONField(blank=True, default=dict, verbose_name='Додаткові налаштування')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
                'db_table': 'content_site_settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='content_site_settings_singleton_id_1')],
            },
        ),
    ]
