# Generated by Django 5.2.15 on 2026-07-27 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_bg', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Фон сторінки')),
                ('color_bg_grey', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Фон сірих секцій')),
                ('color_header_bg', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Фон хедера')),
                ('color_footer_bg', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Фон футера')),
                ('color_header_fg', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Текст хедера')),
                ('color_footer_fg', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Текст футера')),
                ('color_text', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Основний текст')),
                ('color_text_muted', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Приглушений текст')),
                ('color_link', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Посилання')),
                ('color_focus', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Focus ring')),
                ('color_btn_cta', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Кнопка CTA')),
                ('color_btn_cta_hover', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Кнопка CTA (hover)')),
                ('color_btn_search', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Кнопка пошуку')),
                ('color_btn_search_hover', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Кнопка пошуку (hover)')),
                ('color_btn_newsletter', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Кнопка розсилки')),
                ('color_btn_newsletter_hover', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Кнопка розсилки (hover)')),
                ('color_btn_ghost', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Кнопка ghost (текст/бордер)')),
                ('color_btn_ghost_hover_bg', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Кнопка ghost (фон hover)')),
                ('color_badge_cart', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Фон віджета кошика')),
                ('color_badge_yellow', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Бейдж жовтий')),
                ('color_badge_maroon', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Бейдж бордовий')),
                ('color_badge_blue', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Бейдж синій')),
                ('color_badge_gold', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Бейдж золотий')),
                ('color_brand', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Бренд (hover заголовків карток)')),
                ('color_brand_hover', models.CharField(blank=True, default='', help_text='Hex #RRGGBB. Порожньо = дефолт з colors.css.', max_length=7, validators=[django.core.validators.RegexValidator(message='Колір має бути у форматі #RRGGBB або порожнім', regex='^$|^#[0-9A-Fa-f]{6}$')], verbose_name='Бренд hover')),
                ('font_heading', models.CharField(blank=True, choices=[('', 'Дефолт (Georgia)'), ('Georgia, "Times New Roman", "Palatino Linotype", serif', 'Georgia (system)'), ('"Playfair Display", Georgia, serif', 'Playfair Display'), ('"Cormorant Garamond", Georgia, serif', 'Cormorant Garamond'), ('"Libre Baskerville", Georgia, serif', 'Libre Baskerville'), ('"Merriweather", Georgia, serif', 'Merriweather')], default='', help_text='Порожньо = дефолт з CSS.', max_length=120, verbose_name='Шрифт заголовків')),
                ('font_body', models.CharField(blank=True, choices=[('', 'Дефолт (system sans)'), ('system-ui, -apple-system, "Segoe UI", sans-serif', 'System UI'), ('"Source Sans 3", "Segoe UI", system-ui, sans-serif', 'Source Sans 3'), ('"Inter", "Segoe UI", system-ui, sans-serif', 'Inter'), ('"Nunito Sans", "Segoe UI", system-ui, sans-serif', 'Nunito Sans'), ('"DM Sans", "Segoe UI", system-ui, sans-serif', 'DM Sans')], default='', help_text='Порожньо = дефолт з CSS.', max_length=120, verbose_name='Шрифт тексту')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Тема сайту',
                'verbose_name_plural': 'Тема сайту',
                'db_table': 'content_active_theme',
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='content_active_theme_singleton_id_1')],
            },
        ),
    ]
