# Generated by Django 5.2.15 on 2026-07-27 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_card_badge'),
        ('content', '0002_active_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartCrossSellItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Cross-sell товар',
                'verbose_name_plural': 'Cross-sell товари',
                'db_table': 'content_cart_cross_sell_item',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CartPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('empty_title_uk', models.CharField(default='Ваш кошик зараз порожній', max_length=255, verbose_name='Порожній кошик — заголовок')),
                ('empty_text_uk', models.TextField(default='Додайте ноти з каталогу — кошик збережеться в цій сесії браузера.', verbose_name='Порожній кошик — текст')),
                ('recommended_title_uk', models.CharField(default='Рекомендуємо вам', max_length=255, verbose_name='Заголовок рекомендацій')),
                ('cross_sell_title_uk', models.CharField(default='Часто купують разом', max_length=255, verbose_name='Заголовок «Часто купують разом»')),
                ('continue_shopping_label_uk', models.CharField(default='Продовжити покупки', max_length=120, verbose_name='Кнопка «Продовжити покупки»')),
                ('checkout_label_uk', models.CharField(default='Оформити замовлення', max_length=120, verbose_name='Кнопка оформлення')),
                ('cross_sell_products', models.ManyToManyField(blank=True, related_name='+', through='content.CartCrossSellItem', to='catalog.product', verbose_name='Часто купують разом')),
            ],
            options={
                'verbose_name': 'Налаштування кошика',
                'verbose_name_plural': 'Налаштування кошика',
                'db_table': 'content_cart_page_settings',
            },
        ),
        migrations.AddField(
            model_name='cartcrosssellitem',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_sell_items', to='content.cartpagesettings'),
        ),
        migrations.CreateModel(
            name='CartRecommendedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product', verbose_name='Товар')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_items', to='content.cartpagesettings')),
            ],
            options={
                'verbose_name': 'Рекомендований товар',
                'verbose_name_plural': 'Рекомендовані товари',
                'db_table': 'content_cart_recommended_item',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='cartpagesettings',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, related_name='+', through='content.CartRecommendedItem', to='catalog.product', verbose_name='Рекомендовані товари'),
        ),
        migrations.CreateModel(
            name='CartTrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('ssl', 'SSL'), ('payment', 'Оплата'), ('rating', 'Рейтинг'), ('custom', 'Інше')], default='custom', max_length=20, verbose_name='Тип')),
                ('label_uk', models.CharField(max_length=120, verbose_name='Підпис (UK)')),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to='content/cart_badges/', verbose_name='Зображення')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_badges', to='content.cartpagesettings')),
            ],
            options={
                'verbose_name': 'Trust-бейдж кошика',
                'verbose_name_plural': 'Trust-бейджі кошика',
                'db_table': 'content_cart_trust_badge',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cartcrosssellitem',
            constraint=models.UniqueConstraint(fields=('settings', 'product'), name='content_cart_cross_sell_uniq'),
        ),
        migrations.AddConstraint(
            model_name='cartrecommendeditem',
            constraint=models.UniqueConstraint(fields=('settings', 'product'), name='content_cart_recommended_uniq'),
        ),
        migrations.AddConstraint(
            model_name='cartpagesettings',
            constraint=models.CheckConstraint(condition=models.Q(('pk', 1)), name='content_cart_page_settings_singleton_id_1'),
        ),
    ]
