# Generated by Django 5.2.15 on 2026-07-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_footer_gradient_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlead',
            name='topic',
            field=models.CharField(blank=True, choices=[('order', 'Питання по замовленню'), ('sheet', 'Пошук нот'), ('partner', 'Співпраця')], default='', max_length=32, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contacts_json',
            field=models.JSONField(default=dict, help_text='phones, phone_display, email, email_response, hours, address, maps_url, viber, telegram, schedule{timezone,days,open,close}', verbose_name='Контакти'),
        ),
    ]
