# Generated by Django 5.2.15 on 2026-07-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_contact_lead_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_show_payment_cod',
            field=models.BooleanField(default=False, help_text='Картка накладеного платежу на /dostavka-i-oplata/', verbose_name='Оплата: показувати накладений платіж'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_show_payment_iban',
            field=models.BooleanField(default=False, help_text='Картка оплати за реквізитами на /dostavka-i-oplata/', verbose_name='Оплата: показувати IBAN / ФОП'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_show_pickup',
            field=models.BooleanField(default=False, help_text='Картка самовивізу на /dostavka-i-oplata/', verbose_name='Доставка: показувати самовивіз'),
        ),
        migrations.AlterField(
            model_name='contactlead',
            name='topic',
            field=models.CharField(blank=True, choices=[('order', 'Питання по замовленню'), ('sheet', 'Пошук нот')], default='', max_length=32, verbose_name='Тема'),
        ),
    ]
