# Generated by Django 5.2.15 on 2026-07-27 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_shipping_page_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('hero_title_uk', models.CharField(default='NotenHaus — Дім, де оживає музика 🎼', max_length=255, verbose_name='Hero — заголовок')),
                ('hero_subtitle_uk', models.TextField(default='Ми поєднуємо класичні нотні традиції та сучасний цифровий світ для музикантів, викладачів та поціновувачів вишуканого звучання.', verbose_name='Hero — підзаголовок')),
                ('timeline_title_uk', models.CharField(default='Наша Партитура', max_length=255, verbose_name='Timeline — заголовок')),
                ('timeline_lead_uk', models.TextField(blank=True, default='Ключові такти розвитку NotenHaus — від бюро для студентів до спеціалізованого нотного дому.', verbose_name='Timeline — лід')),
                ('values_title_uk', models.CharField(default='Чому музиканти обирають NotenHaus', max_length=255, verbose_name='Цінності — заголовок')),
                ('cta_title_uk', models.CharField(default='Знайдіть свій наступний музичний твір', max_length=255, verbose_name='CTA — заголовок')),
                ('cta_button_uk', models.CharField(default='Переглянути каталог нот ➔', max_length=120, verbose_name='CTA — кнопка')),
                ('meta_description_uk', models.CharField(blank=True, default='Історія, місія та переваги NotenHaus — спеціалізований нотний магазин з офіційними виданнями Urtext, Henle, Bärenreiter.', max_length=160, verbose_name='Meta description')),
            ],
            options={
                'verbose_name': 'Сторінка «Про нас»',
                'verbose_name_plural': 'Сторінка «Про нас»',
                'db_table': 'content_about_page_settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='content_about_page_settings_singleton_id_1')],
            },
        ),
        migrations.CreateModel(
            name='AboutMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_uk', models.CharField(help_text='Показується, якщо лічильник вимкнено або count_target порожній.', max_length=64, verbose_name='Значення (відображення)')),
                ('count_target', models.PositiveIntegerField(blank=True, help_text='Якщо задано — анімація від 0. Порожньо = статичний текст (напр. Instant).', null=True, verbose_name='Ціль лічильника')),
                ('count_suffix', models.CharField(blank=True, default='', help_text='Напр. +, %', max_length=8, verbose_name='Суфікс лічильника')),
                ('label_uk', models.CharField(max_length=255, verbose_name='Підпис')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='content.aboutpagesettings')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'db_table': 'content_about_milestone',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutTimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_uk', models.CharField(max_length=64, verbose_name='Рік / мітка')),
                ('title_uk', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text_uk', models.TextField(verbose_name='Опис')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_items', to='content.aboutpagesettings')),
            ],
            options={
                'verbose_name': 'Timeline-пункт',
                'verbose_name_plural': 'Timeline',
                'db_table': 'content_about_timeline_item',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutValueCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_key', models.CharField(choices=[('book', 'Нотна книга'), ('package', 'Пакування'), ('experts', 'Експерти')], default='book', max_length=20, verbose_name='Іконка')),
                ('title_uk', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text_uk', models.TextField(verbose_name='Текст')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_cards', to='content.aboutpagesettings')),
            ],
            options={
                'verbose_name': 'Картка цінності',
                'verbose_name_plural': 'Картки цінностей',
                'db_table': 'content_about_value_card',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
