# Generated by Django 5.2.15 on 2026-07-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_about_page_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=512, upload_to='content/hero/', verbose_name='Зображення')),
                ('alt_uk', models.CharField(blank=True, default='', max_length=200, verbose_name='Alt (UK)')),
                ('alt_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Alt (EN)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Hero-слайд',
                'verbose_name_plural': 'Hero-слайди',
                'db_table': 'content_hero_slide',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CabinetPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Кабінет — UI',
                'verbose_name_plural': 'Кабінет — UI',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesettings',),
        ),
        migrations.CreateModel(
            name='CartChromeSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Кошик — UI chrome',
                'verbose_name_plural': 'Кошик — UI chrome',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesettings',),
        ),
        migrations.CreateModel(
            name='CatalogPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Каталог — UI',
                'verbose_name_plural': 'Каталог — UI',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesettings',),
        ),
        migrations.CreateModel(
            name='CheckoutPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Checkout — UI',
                'verbose_name_plural': 'Checkout — UI',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesettings',),
        ),
        migrations.CreateModel(
            name='ContactsPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Контакти — тексти',
                'verbose_name_plural': 'Контакти — тексти',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeHeroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Hero',
                'verbose_name_plural': 'Головна — Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeNewSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Новинки',
                'verbose_name_plural': 'Головна — Новинки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomePopularSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Популярні',
                'verbose_name_plural': 'Головна — Популярні',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesettings',),
        ),
        migrations.CreateModel(
            name='SearchPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Пошук — UI',
                'verbose_name_plural': 'Пошук — UI',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesettings',),
        ),
        migrations.CreateModel(
            name='ShippingPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Доставка та оплата',
                'verbose_name_plural': 'Доставка та оплата',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteFooterSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Підвал сайту',
                'verbose_name_plural': 'Підвал сайту',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteHeaderSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Шапка сайту',
                'verbose_name_plural': 'Шапка сайту',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesettings',),
        ),
        migrations.CreateModel(
            name='ThankYouPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Дякуємо — UI',
                'verbose_name_plural': 'Дякуємо — UI',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('site', 'Сайт'), ('shipping', 'Доставка'), ('contacts', 'Контакти'), ('catalog', 'Каталог'), ('search', 'Пошук'), ('cart', 'Кошик'), ('checkout', 'Checkout'), ('thank_you', 'Дякуємо'), ('cabinet', 'Кабінет')], max_length=32, verbose_name='Сторінка')),
                ('key', models.CharField(max_length=64, verbose_name='Ключ')),
                ('label', models.CharField(max_length=128, verbose_name='Мітка')),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Фото'), ('url', 'Посилання'), ('video', 'Відео')], default='text', max_length=16, verbose_name='Тип')),
                ('text_uk', models.TextField(blank=True, default='', verbose_name='Текст (UK)')),
                ('text_en', models.TextField(blank=True, default='', verbose_name='Текст (EN)')),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to='content/blocks/', verbose_name='Зображення')),
                ('link_url', models.CharField(blank=True, default='', max_length=512, verbose_name='URL')),
                ('link_label_uk', models.CharField(blank=True, default='', max_length=128, verbose_name='Текст кнопки (UK)')),
                ('link_label_en', models.CharField(blank=True, default='', max_length=128, verbose_name='Текст кнопки (EN)')),
                ('video_embed_url', models.URLField(blank=True, default='', verbose_name='Embed URL')),
                ('video_file', models.FileField(blank=True, max_length=512, null=True, upload_to='content/blocks/video/', verbose_name='Відеофайл')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'CMS-блок',
                'verbose_name_plural': 'CMS-блоки',
                'db_table': 'content_site_block',
                'ordering': ['page', 'sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='content_site_block_page_key_uniq')],
            },
        ),
    ]
