# Generated by Django 5.2.15 on 2026-07-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_site_block_hero_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmilestone',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Підпис (EN)'),
        ),
        migrations.AddField(
            model_name='aboutmilestone',
            name='value_en',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Значення (EN)'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='cta_button_en',
            field=models.CharField(blank=True, default='Browse the catalog ➔', max_length=120, verbose_name='CTA — кнопка (EN)'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='cta_title_en',
            field=models.CharField(blank=True, default='Find your next musical piece', max_length=255, verbose_name='CTA — заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='hero_subtitle_en',
            field=models.TextField(blank=True, default='We combine classical sheet-music traditions with the modern digital world for musicians, teachers and lovers of refined sound.', verbose_name='Hero — підзаголовок (EN)'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='hero_title_en',
            field=models.CharField(blank=True, default='NotenHaus — Where music comes alive 🎼', max_length=255, verbose_name='Hero — заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='meta_description_en',
            field=models.CharField(blank=True, default='History, mission and strengths of NotenHaus — a specialized sheet-music store with official Urtext, Henle and Bärenreiter editions.', max_length=160, verbose_name='Meta description (EN)'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='timeline_lead_en',
            field=models.TextField(blank=True, default='Key measures in NotenHaus growth — from a student bureau to a specialized sheet-music house.', verbose_name='Timeline — лід (EN)'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='timeline_title_en',
            field=models.CharField(blank=True, default='Our Score', max_length=255, verbose_name='Timeline — заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='values_title_en',
            field=models.CharField(blank=True, default='Why musicians choose NotenHaus', max_length=255, verbose_name='Цінності — заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='abouttimelineitem',
            name='text_en',
            field=models.TextField(blank=True, default='', verbose_name='Опис (EN)'),
        ),
        migrations.AddField(
            model_name='abouttimelineitem',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='abouttimelineitem',
            name='year_en',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Рік / мітка (EN)'),
        ),
        migrations.AddField(
            model_name='aboutvaluecard',
            name='text_en',
            field=models.TextField(blank=True, default='', verbose_name='Текст (EN)'),
        ),
        migrations.AddField(
            model_name='aboutvaluecard',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='cartpagesettings',
            name='checkout_label_en',
            field=models.CharField(blank=True, default='Checkout', max_length=120, verbose_name='Кнопка оформлення (EN)'),
        ),
        migrations.AddField(
            model_name='cartpagesettings',
            name='continue_shopping_label_en',
            field=models.CharField(blank=True, default='Continue shopping', max_length=120, verbose_name='Кнопка «Продовжити покупки» (EN)'),
        ),
        migrations.AddField(
            model_name='cartpagesettings',
            name='cross_sell_title_en',
            field=models.CharField(blank=True, default='Frequently bought together', max_length=255, verbose_name='Заголовок «Часто купують разом» (EN)'),
        ),
        migrations.AddField(
            model_name='cartpagesettings',
            name='empty_text_en',
            field=models.TextField(blank=True, default='Add scores from the catalog — the cart is saved for this browser session.', verbose_name='Порожній кошик — текст (EN)'),
        ),
        migrations.AddField(
            model_name='cartpagesettings',
            name='empty_title_en',
            field=models.CharField(blank=True, default='Your cart is empty', max_length=255, verbose_name='Порожній кошик — заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='cartpagesettings',
            name='recommended_title_en',
            field=models.CharField(blank=True, default='Recommended for you', max_length=255, verbose_name='Заголовок рекомендацій (EN)'),
        ),
        migrations.AddField(
            model_name='carttrustbadge',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Підпис (EN)'),
        ),
        migrations.AlterField(
            model_name='aboutmilestone',
            name='label_uk',
            field=models.CharField(max_length=255, verbose_name='Підпис (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutmilestone',
            name='value_uk',
            field=models.CharField(help_text='Показується, якщо лічильник вимкнено або count_target порожній.', max_length=64, verbose_name='Значення (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='cta_button_uk',
            field=models.CharField(default='Переглянути каталог нот ➔', max_length=120, verbose_name='CTA — кнопка (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='cta_title_uk',
            field=models.CharField(default='Знайдіть свій наступний музичний твір', max_length=255, verbose_name='CTA — заголовок (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='hero_subtitle_uk',
            field=models.TextField(default='Ми поєднуємо класичні нотні традиції та сучасний цифровий світ для музикантів, викладачів та поціновувачів вишуканого звучання.', verbose_name='Hero — підзаголовок (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='hero_title_uk',
            field=models.CharField(default='NotenHaus — Дім, де оживає музика 🎼', max_length=255, verbose_name='Hero — заголовок (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='meta_description_uk',
            field=models.CharField(blank=True, default='Історія, місія та переваги NotenHaus — спеціалізований нотний магазин з офіційними виданнями Urtext, Henle, Bärenreiter.', max_length=160, verbose_name='Meta description (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='timeline_lead_uk',
            field=models.TextField(blank=True, default='Ключові такти розвитку NotenHaus — від бюро для студентів до спеціалізованого нотного дому.', verbose_name='Timeline — лід (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='timeline_title_uk',
            field=models.CharField(default='Наша Партитура', max_length=255, verbose_name='Timeline — заголовок (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='values_title_uk',
            field=models.CharField(default='Чому музиканти обирають NotenHaus', max_length=255, verbose_name='Цінності — заголовок (UK)'),
        ),
        migrations.AlterField(
            model_name='abouttimelineitem',
            name='text_uk',
            field=models.TextField(verbose_name='Опис (UK)'),
        ),
        migrations.AlterField(
            model_name='abouttimelineitem',
            name='title_uk',
            field=models.CharField(max_length=255, verbose_name='Заголовок (UK)'),
        ),
        migrations.AlterField(
            model_name='abouttimelineitem',
            name='year_uk',
            field=models.CharField(max_length=64, verbose_name='Рік / мітка (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutvaluecard',
            name='text_uk',
            field=models.TextField(verbose_name='Текст (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutvaluecard',
            name='title_uk',
            field=models.CharField(max_length=255, verbose_name='Заголовок (UK)'),
        ),
        migrations.AlterField(
            model_name='cartpagesettings',
            name='checkout_label_uk',
            field=models.CharField(default='Оформити замовлення', max_length=120, verbose_name='Кнопка оформлення (UK)'),
        ),
        migrations.AlterField(
            model_name='cartpagesettings',
            name='continue_shopping_label_uk',
            field=models.CharField(default='Продовжити покупки', max_length=120, verbose_name='Кнопка «Продовжити покупки» (UK)'),
        ),
        migrations.AlterField(
            model_name='cartpagesettings',
            name='cross_sell_title_uk',
            field=models.CharField(default='Часто купують разом', max_length=255, verbose_name='Заголовок «Часто купують разом» (UK)'),
        ),
        migrations.AlterField(
            model_name='cartpagesettings',
            name='empty_text_uk',
            field=models.TextField(default='Додайте ноти з каталогу — кошик збережеться в цій сесії браузера.', verbose_name='Порожній кошик — текст (UK)'),
        ),
        migrations.AlterField(
            model_name='cartpagesettings',
            name='empty_title_uk',
            field=models.CharField(default='Ваш кошик зараз порожній', max_length=255, verbose_name='Порожній кошик — заголовок (UK)'),
        ),
        migrations.AlterField(
            model_name='cartpagesettings',
            name='recommended_title_uk',
            field=models.CharField(default='Рекомендуємо вам', max_length=255, verbose_name='Заголовок рекомендацій (UK)'),
        ),
    ]
