# Generated by Django 5.2.15 on 2026-07-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_about_cart_en_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttrustbadge',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендований розмір: 128×128 px. Значно більші фото автоматично масштабуються (без обрізки). JPG/PNG → WebP.', max_length=512, null=True, upload_to='content/cart_badges/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='Рекомендований розмір: 1920×1080 px. Значно більші фото автоматично обрізаються та стискаються. JPG/PNG → WebP.', max_length=512, upload_to='content/hero/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендований розмір залежить від блоку (див. підказку в формі). Значно більші фото автоматично обробляються. JPG/PNG → WebP.', max_length=512, null=True, upload_to='content/blocks/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Рекомендований розмір: 480×160 px. Значно більші фото автоматично масштабуються (без обрізки). JPG/PNG → WebP.', max_length=512, null=True, upload_to='content/logo/', verbose_name='Логотип'),
        ),
    ]
