# Generated by Django 5.2.15 on 2026-07-27 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0002_product_card_badge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cabinet_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Імʼя')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Профіль клієнта',
                'verbose_name_plural': 'Профілі клієнтів',
                'db_table': 'cabinet_customer_profile',
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='catalog.product', verbose_name='Нота')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Позиція обраного',
                'verbose_name_plural': 'Обране',
                'db_table': 'cabinet_wishlist_item',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='cabinet_wishlist_item_uniq')],
            },
        ),
    ]
